// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChTIF1UEKwS0JLgjX8J2lBMsJC9j3Hhyk',
    appId: '1:12714085452:web:fb4a97f64431612212b8e9',
    messagingSenderId: '12714085452',
    projectId: 'colorblendr',
    authDomain: 'colorblendr.firebaseapp.com',
    storageBucket: 'colorblendr.appspot.com',
    measurementId: 'G-P55FPLDWVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARbHFmuGp8PEYRjb1B5XVRgfZeOzQvUYQ',
    appId: '1:12714085452:android:e0e54be0f001fb8712b8e9',
    messagingSenderId: '12714085452',
    projectId: 'colorblendr',
    storageBucket: 'colorblendr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq-HKmJjUE3yw05boCGtVUsGzVGoGyBlo',
    appId: '1:12714085452:ios:6b3187f929ca24ef12b8e9',
    messagingSenderId: '12714085452',
    projectId: 'colorblendr',
    storageBucket: 'colorblendr.appspot.com',
    iosBundleId: 'org.ColorBlendr.colorBlendr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq-HKmJjUE3yw05boCGtVUsGzVGoGyBlo',
    appId: '1:12714085452:ios:73d156af666022f112b8e9',
    messagingSenderId: '12714085452',
    projectId: 'colorblendr',
    storageBucket: 'colorblendr.appspot.com',
    iosBundleId: 'org.ColorBlendr.colorBlendr.RunnerTests',
  );
}
